version: '3.9'

services:
  todo-postgres:
    image: postgres
    container_name: todo-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: '$DB_NAME'
      POSTGRES_USER: '$DB_USER'
      POSTGRES_PASSWORD: '$DB_PASS'
    volumes:
      - /var/lib/todo-postgres:/var/lib/postgresql/data
    ports:
      - '$DB_PORT:5432'
    networks:
      - wedding_network

networks:
  wedding_network:
    driver: bridge